apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672
      name: traffic
    - port: 15672
      targetPort: 15672
      name: management
